######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 7 21:44:41 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qvolume.h
SOURCES += main.cpp qvolume.cpp
